"""empty message

Revision ID: 47345eb383e8
Revises: 69f121fe0731
Create Date: 2024-02-01 14:39:30.911991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47345eb383e8'
down_revision = '69f121fe0731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outreach')
    op.add_column('contact', sa.Column('connected', sa.Boolean(), nullable=True))
    op.add_column('contact', sa.Column('sent_messages', sa.Integer(), nullable=True))
    op.add_column('contact', sa.Column('replied', sa.Boolean(), nullable=True))
    op.add_column('contact', sa.Column('tone', sa.Boolean(), nullable=True))
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.drop_column('contact', 'outreach_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('outreach_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'contact', 'outreach', ['outreach_id'], ['id'])
    op.drop_column('contact', 'tone')
    op.drop_column('contact', 'replied')
    op.drop_column('contact', 'sent_messages')
    op.drop_column('contact', 'connected')
    op.create_table('outreach',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('connected', sa.BOOLEAN(), nullable=True),
    sa.Column('sent_messages', sa.INTEGER(), nullable=True),
    sa.Column('replied', sa.BOOLEAN(), nullable=True),
    sa.Column('tone', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
