"""empty message

Revision ID: 69f121fe0731
Revises: 9f828d15f559
Create Date: 2024-01-31 15:47:39.908883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f121fe0731'
down_revision = '9f828d15f559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('open_positions', 'date_posted')
    op.drop_column('outreach', 'recent_interaction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outreach', sa.Column('recent_interaction', sa.DATETIME(), nullable=True))
    op.add_column('open_positions', sa.Column('date_posted', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
