"""empty message

Revision ID: 9f828d15f559
Revises: 
Create Date: 2024-01-29 16:22:34.053361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f828d15f559'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount_of_employees', sa.String(), nullable=True),
    sa.Column('total_open_positions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outreach',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=True),
    sa.Column('sent_messages', sa.Integer(), nullable=True),
    sa.Column('replied', sa.Boolean(), nullable=True),
    sa.Column('tone', sa.Boolean(), nullable=True),
    sa.Column('recent_interaction', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outreach_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('length_of_position', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['outreach_id'], ['outreach.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('open_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('salary_range', sa.String(), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('position_status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('open_positions')
    op.drop_table('contact')
    op.drop_table('outreach')
    op.drop_table('companies')
    # ### end Alembic commands ###
